### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by codeholic** [bilus/rspec-cramp#3]
The latest version of cramp (0.15.3) depends on rack '~> 1.5.2', whereas the latest version of rspec-cramp (0.1.2) depends on rake '~> 1.3.2'.

**Comment by bilus** [comment]
@Ivan, thanks! I've just pushed version 0.13, it should fix the problem.
Please let me know.

**Comment by codeholic** [comment]
It works now. Thanks!
